[project]
name = "gplearn"
version = "0.5.dev1"
description = "Genetic Programming in Python"
readme = "README.rst"
authors = [{name = "xuan qi"}]
license = {file = "LICENSE"}
requires-python = ">=3.8"
dependencies = [
    "scikit-learn>=1.0.2",
    "joblib>=1.0.0"
]

[build-system]
requires = ["hatchling>=1.18.0"]
build-backend = "hatchling.build"